name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          cname: ghdocs.yunloong.cn # if wanna deploy to custom domain
      - uses: manyuanrong/setup-ossutil@v3.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: 'oss-cn-hongkong.aliyuncs.com'
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - name: Deply To Aliyun OSS
        run: ossutil cp -rf docs/.vitepress/dist oss://${{ secrets.BUCKET_NAME }}/
